name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build and push 🚢
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      REPO: ${{ github.event.repository.name }}

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          TAG=$(echo ${{ github.ref_name }} | sed 's/^v//')
          echo "TAG=$TAG" >> $GITHUB_ENV
          echo "The tag for this build is $TAG"
          echo "The repo name is: $REPO"

      - id: auth-google
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: 'open-targets-eu-dev'
          workload_identity_provider: projects/426265110888/locations/global/workloadIdentityPools/github-actions/providers/opentargets
          service_account: github-actions@open-targets-eu-dev.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - id: auth-gar
        name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: europe-west1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth-google.outputs.access_token }}

      - id: auth-ghcr
        name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: push
        name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.TAG }}
            europe-west1-docker.pkg.dev/open-targets-eu-dev/${{ env.REPO }}/${{ env.REPO }}:latest
            europe-west1-docker.pkg.dev/open-targets-eu-dev/${{ env.REPO }}/${{ env.REPO }}:${{ env.TAG }}

      - id: generate-attestations
        name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: europe-west1-docker.pkg.dev/open-targets-eu-dev/${{ env.REPO }}/${{ env.REPO }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
